### ISSUE TITLE
Wrong grading 5+ answer option

### ISSUE THREAD

**Issue by tkorner** [ndunand/moodle-qtype_matrix#13]
as described in the mail, If 5 or more options are gradable and more than 4 answers are correct 0 Points are given for them (see attachment),
![bildschirmfoto von safari 28 05 14 15 32 29](https://cloud.githubusercontent.com/assets/3245718/3105312/9f8d1882-e671-11e3-8d76-0daa21d6b2d8.jpg)
 
thus:

please change to "if 60% an more are correct" then half of the points. if all, all points, if less then 60% zero points".

<b>wording </b> (old: Kprime: If “Kprime” is selected the student receives one point, if all of his answers are correct, and a half point if three of his answers are correct, else zero points.)

New
Kprime: The student receives one point, if all responses are correct, half a point if 60% ore more responses are correct, and zero points otherwise.

Kprim: Bei der Auswahl „Kprim“ erhalten Kandidaten einen Punkt, wenn alle Teilaussagen richtig bewertet wurden, einen halben Punkt, wenn mindestens 60% als richtig bewertet wurden und null Punkte sonst.

**Comment by laurentopprecht** [comment]
Working for me

![image](https://cloud.githubusercontent.com/assets/1706006/9225627/d3db2eea-410a-11e5-9241-4bcc21e59caa.png)
