### ISSUE TITLE
wrong grading for kprim with multiple answers

### ISSUE THREAD

**Issue by isacsonk** [ndunand/moodle-qtype_matrix#16]
how to reproduce:
1) go to the question bank in the course Testkurs KI
2) choose category Matrix
3) click on the preview-Symbol next to the question "Kprim mehrere Antworten"
4) select all options (answer statements) as correct (richtig)
--> you receive full points although option "b beide" was not responded to correctly. The correct answer of "b beide" is when both responses "richtig" and "falsch" are selected. (This doesn't really make sense of course, but if you had other response labels it could make sense). 

requirement:
in the above mentioned case you should only get full points, when all the rows are answered correctly.
![kprimmultipleanswerwrong](https://cloud.githubusercontent.com/assets/7068702/3358405/a1a8d3f6-fadd-11e3-8c53-8e880c7ce53a.PNG)
![kprimmultipleanswer](https://cloud.githubusercontent.com/assets/7068702/3358406/a3c668ba-fadd-11e3-8c40-e0a5bcdd4671.PNG)

**Comment by laurentopprecht** [comment]
The kprime (any grading) works as intended: 

At least one correct answer, no invalid answers

For a pure kprime the user can use kprime (0/1).

Arguably the wording is a bit misleading and we could replace "kprime" by "kprime any correct" or whatever is seen as better.

**Comment by laurentopprecht** [comment]
Having a look at the translation files the meanings do not match.
I changed the English wording to correct that.
