### ISSUE TITLE
changing anything in a kprime question after the question has been solved by a student, results in loss of the students response

### ISSUE THREAD

**Issue by isacsonk** [ndunand/moodle-qtype_matrix#18]
how to reproduce
-----------------------
1. Create a test with kprime questions
2. Solve the test as a student
3. log in as teacher and display the questions
4. enter one question and change something in the question, the answer statements or the responses, save changes
--> the responses the student made are lost

requirement
-----------------
responses of the students should persist, even when the question is edited.

remark
----------
the correct mark is still there, but we also need the responses to persist.

**Comment by laurentopprecht** [comment]
Tested and working but for the change from multiple to non-multiple

**Comment by laurentopprecht** [comment]
Changing from multiple to non-multiple fixed
