### ISSUE TITLE
Kprime with exactly 4 options, no multiple responses possible

### ISSUE THREAD

**Issue by isacsonk** [ndunand/moodle-qtype_matrix#20]
Description
--------------------
Some of the bugs are obsolete if we change the kprime/matrix question to a kprime question with only the configuration options we wanted to have in the first place.

Requirements
-------------------
1) Remove configuration option "Allow multiple responses per answer statement?" ( -->#16, and #17 can be closed)
2) Remove possibility (plus sign) to add more answer statements and remove possibility to add more responses and remove possibility to have less than 4 answer statements and remove possibility to have less than 2 responses (-->#13 can be closed)
3) Change label from Matrix/Kprime to Kprime and change wordings in popup help

For more details see comments below.

**Comment by laurentopprecht** [comment]
This request does not relate to our situation. 
The matrix plugin is meant to create matrix questions, not only kprime.
Closing
