### ISSUE TITLE
what are the extra WYSIWYG fields used for?

### ISSUE THREAD

**Issue by ndunand** [ndunand/moodle-qtype_matrix#25]
There are extra Moodle HTML editors available within editing the matrix in the back-end ('...' buttons toggle their display):

1. one for each subquestion item (left of the matrix) : is displayed in the question form as a description of each item – is it really necessary?
2. one for each column title (top of the matrix) : I can't get to display it anywhere -> bug?
3. one "comment" for each subquestion item (right of the matrix) : can act as a feedback for each subquestion – this seems to be relevant to me.

**Comment by laurentopprecht** [comment]
1
Those are for descriptions/hints. We could check with Daniel whether this is actually required but it was part of the original requirements. I

If those are not needed by some we can hide them through CSS uging the theme. Possibly adding classe helpers if required.

2
I believe we may need to do additional tests with different themes/versions. Can you tell us what version/theme you are using? Or what exactly is the problem?

**Comment by laurentopprecht** [comment]
Meeting:
OK to leave
Theme related issues should be fixed in the theme. That is unless there is a signifcant problem we can/should resolve for all themes. Tested OK with the Clean theme.
