### ISSUE TITLE
Grading methods listed are inconsistent

### ISSUE THREAD

**Issue by ndunand** [ndunand/moodle-qtype_matrix#26]
This has already been discussed, but here for proper tracking only:

The choice of grading methods does not correspond to the documentation (in French). Make sure all statements are correct.

**Comment by laurentopprecht** [comment]
Yes some gradings have been removed from the original work. 

We need to clarify what gradings are actually required. We can discuss that on Friday.

**Comment by laurentopprecht** [comment]
Per meeting we don't (re-)add additional grading methods. Not needed.
Translation updated.
