### ISSUE TITLE
student can't answer partially

### ISSUE THREAD

**Issue by ndunand** [ndunand/moodle-qtype_matrix#27]
A selection has to be made for each row: is this the intended behavior?

If no selection has been selected for one (or more) rows, the question engine won't accept the answer, categorizing it as invalid.

**Comment by laurentopprecht** [comment]
That's a requirement's question for Daniel.

**Comment by laurentopprecht** [comment]
Per meeting this is OK

**Comment by juangross** [comment]
Is possible to reopen this issue?. It would be useful to be able to change this behavior.
if a student answers only a few questions, they should get a score for them.

**Comment by ndunand** [comment]
@juangross ,

We are looking into possibly enhancing this plugin over the next Moodle release cycle. Could you please state precisely the current behavior vs. the desired behavior? It would be possible to have a default (current behavior) that could be changed.

**Comment by juangross** [comment]
> @juangross ,
> 
> We are looking into possibly enhancing this plugin over the next Moodle release cycle. Could you please state precisely the current behavior vs. the desired behavior? It would be possible to have a default (current behavior) that could be changed.


The current behavior if you create a question using the scoring method "subpoints":
![image](https://user-images.githubusercontent.com/8507691/108504976-7e531600-7295-11eb-9715-5018bef1d335.png)

if the student answer all rows, the system will score the answer with the complete point:
![image](https://user-images.githubusercontent.com/8507691/108505114-afcbe180-7295-11eb-94af-be554107c3ef.png)


However, if the student answer only a few rows, the system interpret that the question is " not answered".
![image](https://user-images.githubusercontent.com/8507691/108506419-81e79c80-7297-11eb-9ff2-8e02ddc29ff1.png)

In this case, I think the desired behavior should be that the student should receive a fraction of the total score, proportional to the correctly answered rows.

**Comment by MarkusPiotrowski** [comment]
I also agree that the plugin's interpretation of a partially answered question as "not answered" is counter-intuitive (or misleading), for both the students and the supervisor. 
The correct rows are marked as correct byt the plugin (as seen in the example above) but no mark is awarded. When "Subpoints" is selected as scoring method, correct rows should give subpoints. A row with no selection is wrong, but that should not affect the scoring of the other rows.

**Comment by GIBZ-GIPE** [comment]
This issue seems to be open for quite some time now. I'm very interested in having this fixed as @juangross described in his post in mid February last year.
Any news so far? Could the upcoming release of Moodle 4.0 with some improvements regarding the exams possibly be a target for having this "strange" behavior for the "subpoints" grading mode fixed?

Also: Thanks to all developers/maintainers of this repository - I'm overall quite happy with this question type.

**Comment by melanietreitinger** [comment]
I'm also very interested in having this behaviour changed or maybe turned into an option.

**Comment by ndunand** [comment]
That's good to hear @relecand , thanks for posting and for sharing. We're still in the process to evaluate #58 but it's on our list as well.

**Comment by relecand** [comment]
Could be closed now.

**Comment by ndunand** [comment]
Thanks for posting back @relecand 
Closing now
