### ISSUE TITLE
Spelling error: $resut instead of $result

### ISSUE THREAD

**Issue by cdsmith-umn** [ndunand/moodle-qtype_matrix#33]
This has been in your code for a very long time and we've been patching it in our installation every time  we install a new version of this plugin. I'm surprised it hasn't been corrected long ago and so I decided to open an issue for it.

https://github.com/ndunand/moodle-qtype_matrix/blob/master/qtype_matrix_grading.class.php#L55

Thank you for fixing this.

**Comment by NicoAlexH** [comment]
fixed by 907bae43d1905809b5b87fffe987dee878822770
