### ISSUE TITLE
MATRIX question acces denied

### ISSUE THREAD

**Issue by Roussxx** [ndunand/moodle-qtype_matrix#44]
Hello,
I use Moodle 3.4
Since the update to the last plugin, I no longer have access to questions MATRIX.
I previously used qtype_matrix_moodle33_2017062900 plugin, it was OK
When I want to modify a MATRIX type question, MATRIX I do not have access to it.
When one or more MATRIX questions are in a quiz, the quiz can not be started.
error message in french moodle plateforme is «erreur base de donnée», than " Erreur de programmation détectée. Ceci doit être corrigé par un programmeur : This behaviour (interactivecountback) cannot work with this question (qtype_missingtype_question)"
thks

**Comment by ndunand** [comment]
Hello,

Thanks for reporting. Looking at the code, it is normal that most question types (including Matrix) would not work with that specific quiz behaviour.

Also, I could not reproduce this error in my test platform. To further investigate, could you provide the following information?

1. which question type plugins are installed in your Moodle
2. which question behaviour plugins are installed in your Moodle
3. a step-by-step walkthrough on how to reproduce this error
