### ISSUE TITLE
Import Export over XML-file

### ISSUE THREAD

**Issue by minhduchoang195** [ndunand/moodle-qtype_matrix#48]
There is still no possiblity for importing and exporting Matrix-questions with Moodle XML format.  This fix relates to commit of issues 46 "https://github.com/ndunand/moodle-qtype_matrix/issues/46" and can only works with the changes of this commit.

**Comment by minhduchoang195** [comment]
Realize Import- and Export-function over  Moodle XML format through overwriting the functions: export_to_xml and import_from_xml.

**Comment by ndunand** [comment]
Thanks for the fix ! This is now merged and will be released soon
