### ISSUE TITLE
Matrix question name style

### ISSUE THREAD

**Issue by cli-ish** [ndunand/moodle-qtype_matrix#59]
Is there a specific reason for the white background of the name field?

![grafik](https://user-images.githubusercontent.com/22986332/213985296-99ec39b9-eade-43f9-8d98-408fec7c6a8d.png)

This is not common with the other question fields and looks a bit strange with it. Would it be possible for me to create a PR that corrects this appearance?

**Comment by ndunand** [comment]
Hi @cli-ish , yes sure it'd make sense to remove this specific styling.
